services:
  backend:
    environment:
      - BACKEND_PORT=5000
      - API_PATH=/api
      - NODE_ENV=production  # Run backend in production mode
      - PORT=5000  # Backend server port
      - LOG_LEVEL=debug  # Control backend logging verbosity
      - PROMETHEUS_METRICS_ENABLED=true  # Enable Prometheus metrics (if needed)
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - monitoring

  frontend:
    environment:
      - REACT_APP_LOG_LEVEL=debug
      - REACT_APP_API_BASE_URL=http://backend:5000  # Base API URL for frontend requests
      - NODE_ENV=production  # Ensures React runs in production mode
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - monitoring
    volumes:
      - ./frontend/conf.d:/etc/nginx/conf.d

  frontend-monitor:
    build: ./frontend
    command: ["sh", "-c", "export NODE_PATH=/monitoring/node_modules && node /server.js"]
    environment:
      - NODE_PATH=/monitoring/node_modules
      - METRICS_PORT=3001
      - METRICS_PATH=/metrics
    ports:
      - "3003:3001"
    depends_on:
      - frontend
    networks:
      - monitoring

  prometheus:      
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    environment:
      - PROMETHEUS_CONFIG=/etc/prometheus/prometheus.yml
      - PROMETHEUS_STORAGE_TSDB_RETENTION_TIME=15d  # Keep data for 15 days
     #- PROMETHEUS_WEB_ENABLE_ADMIN_API=true        # Enable admin API
     #- PROMETHEUS_WEB_BASIC_AUTH_USERNAME=admin    # Basic auth
     #- PROMETHEUS_WEB_BASIC_AUTH_PASSWORD=secure   # Basic auth password
   #- PROMETHEUS_WEB_ENABLE_ADMIN_API=true
    #- PROMETHEUS_WEB_ENABLE_LIFECYCLE=true
    #- PROMETHEUS_WEB_BASIC_AUTH_USERNAME=admin
    #- PROMETHEUS_WEB_BASIC_AUTH_PASSWORD=secure_password
    # Storage settings
    #- PROMETHEUS_STORAGE_TSDB_RETENTION_TIME=15d
    #- PROMETHEUS_STORAGE_TSDB_RETENTION_SIZE=5GB
    # Web settings
    #- PROMETHEUS_WEB_EXTERNAL_URL=http://prometheus:9090
    #- PROMETHEUS_WEB_ROUTE_PREFIX=/
    # Performance tuning
    #- PROMETHEUS_STORAGE_TSDB_WAL_COMPRESSION=true
    #- PROMETHEUS_QUERY_MAX_SAMPLES=50000000

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=steve
      - GF_SECURITY_ADMIN_PASSWORD=gindi
      - GF_USERS_ALLOW_SIGN_UP=false  # Disable user signups
      - GF_LOG_LEVEL=debug  # Increase Grafana logging level
      - GF_DATABASE_TYPE=sqlite3  # Ensure database is set
      - GF_PATHS_PROVISIONING=/usr/share/grafana/conf/provisioning # Ensure dashboards are provisioned
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/usr/share/grafana/dashboards  # ✅ Mount dashboards correctly
      - ./monitoring/grafana/provisioning/datasources:/usr/share/grafana/conf/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/usr/share/grafana/conf/provisioning/dashboards   # ✅ Mount provisioning settings
    ports:
      - "3002:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  grafana-storage:
  prometheus-data:  