global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:5000']

  - job_name: 'frontend'
    metrics_path: /metrics
    static_configs:
      - targets: ['frontend-monitor:3001']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
